name: build container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # build multi-arch images
  jobs-build-images:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Login to Quay.io Registry
      run: docker login -u=${{ secrets.DOCKERHUB_USERNAME }} -p=${{ secrets.DOCKERHUB_PASSWORD }} quay.io

    - name: build multi-arch image
      run: ./build_container/docker_build.sh `date +'%Y-%m-%d'`
